### ISSUE TITLE
Missing mega icons

### ISSUE THREAD

**Issue by aronnebrivio** [nileplumb/PkmnShuffleMap#11]
Hi, actually mega evolutions and mega egg icons are missing.
Today probably a mega tier will appear in Pokémon GO with Mega Venusaur, Blastoise and Charizard.

Are you planning to add these icons to the set?

Thanks

**Comment by nileplumb** [comment]
they're not missing I have the assets already we don't have proto Id yet so they're not uploaded absolutely no map or bot is prepared for them yet.
