### ISSUE TITLE
missing shiny ponyta galarian and shiny rapidash galarian

### ISSUE THREAD

**Issue by pitichou** [nileplumb/PkmnShuffleMap#13]
everything is in the title ;)

**Comment by nileplumb** [comment]
you jms412? if so you know I got them already :p

**Comment by pitichou** [comment]
i don't  know who is jms412 and i just checked again but i can't find them...
Ponyta: ok
Ponyta-shiny: ok
Ponyta-Galarian: ok
Ponyta-Galarian-Shiny: ???

Same for Rapidash...
could you give me the file name please ?

**Comment by nileplumb** [comment]
ah no worries, some  other icon repo manager messaged me yesterday on discord about them, I just haven't pushed them yet :)

**Comment by nileplumb** [comment]
will push this later today

**Comment by nileplumb** [comment]
fixed also popped in the galar forms of birds, corsola and slowking, form protos arent available for birds yet so they'll need a renaming and ICONS index updating once available. but hopefully we'll be on UICONS then :-D
