### ISSUE TITLE
Wrong name on Alolan Golem

### ISSUE THREAD

**Issue by albinlog** [nileplumb/PkmnShuffleMap#15]
First of all - fantastic repo you created! Love the art!

To my point. I found a typo on the file name of Alolan Golem. This is within 'ICONS_STANDARD/pokemon/' at least.

The non-shiny version has this name: 76-72.png
But the shiny version has this name: 76-f72-shiny.png

It's missing an 'f' in the filename for the non-shiny.

**Comment by nileplumb** [comment]
Good spot and same with UICONS too away from workstation at the moment so can't fix

**Comment by nileplumb** [comment]
fixed if you spot any more let me know
