### ISSUE TITLE
Another typo

### ISSUE THREAD

**Issue by albinlog** [nileplumb/PkmnShuffleMap#18]
Hi! 

When I was using your awesome sprites for a small application I came across one more typo in the file names. This time it's Wartortle with sunglasses who has it's filename misspelled. 

8-5.png should be 8-c5.png to follow the standard on the other files. (Shiny is correct thou)

I found this in STANDARD_ICONS - do not know if the problem exist in other folders. 

Best regards
Albin

**Comment by nileplumb** [comment]
Hi Albin, hopefully ICONS will be phased out very soon in favour of UICONS but cheers for bringing to my attention

**Comment by albinlog** [comment]
Hi!

OK - should I use UICONS instead in the future if I want to be up-to-date?

Thank you for quick reply!
