### ISSUE TITLE
missing plant burmy 412_f118.png + 412_f118_s.png

### ISSUE THREAD

**Issue by ReuschelCGN** [nileplumb/PkmnShuffleMap#21]
https://raw.githubusercontent.com/nileplumb/PkmnShuffleMap/master/UICONS/pokemon/412_f118.png
https://raw.githubusercontent.com/nileplumb/PkmnShuffleMap/master/UICONS/pokemon/412_f118_s.png

**Comment by nileplumb** [comment]
Plant burmy isn't missing your project isn't implementing UICONS correctly with fallback if it's creating errors.

412 and 412_s are plant
