### ISSUE TITLE
Missing and wrong file names

### ISSUE THREAD

**Issue by xrated86** [nileplumb/PkmnShuffleMap#29]
Some observations:

- Linoone  (non shiny and shiny): UICONS/pokemon/264.png UICONS/pokemon/264_s.png are reversed
- Deerling Summer (non shiny): UICONS/pokemon/585_f585.png missing

Great work, thanks in advance for correcting :)

**Comment by nileplumb** [comment]
Linoone is fine what you on about?
585_f585 should fallback to 585. What are you using that the project hasn't implemented the fallback?

**Comment by xrated86** [comment]
Please don't take this personally; I'm simply offering feedback.

- Regarding Linoone's appearance, the face coloration seems off, particularly the absence of the white and brownish hues found in the original Pokémon.

- I've implemented my own frontend. While it does have a fallback, it searches for specific form images when defined, which currently seems to be missing. I find this approach somewhat inconsistent in its execution.

**Comment by nileplumb** [comment]
Linoone directly ripped from shuffle https://archives.bulbagarden.net/media/upload/d/d4/Shuffle264.png
Normal linoone. from repo https://raw.githubusercontent.com/nileplumb/PkmnShuffleMap/master/UICONS/pokemon/264.png

You'll see these are the same.

Shiny edited Linoone. from repo https://raw.githubusercontent.com/nileplumb/PkmnShuffleMap/master/UICONS/pokemon/264_s.png (most definitely different from the standard version and more akin to the shiny https://archives.bulbagarden.net/media/upload/0/0d/GO0264_s.png )

Granted most original shiny edits aren't from me and were kindly sent to me when i first started the repo and a fair few are unfortunately a few pixels off centre when compared to their original rips, I often correct this and entirely re-edit the ripped image if I have to make a costume version (or occasionally fully re-create from scratch at a larger resolution, sometimes as a vectors)

Sounds like your fallback code method needs work, as f585 is not defined in my UICONS index (other than the shiny form) feel free to join the Creators discord group and share your project or get advice/examine code from others who have implemented UICONS into their projects.
https://github.com/UIcons/UIcons https://discord.gg/cG8JwrJB6Z

**Comment by xrated86** [comment]
Thank you for your comment!

I've joined the Discord and implemented a workaround in our frontend to handle missing images using the index.json you provided. I appreciate your time and effort. Keep up the excellent work!
